### ISSUE TITLE
Axes crashing the game

### ISSUE THREAD

**Issue by unweeked** [TeamGalena/copperative#17]
### What happened?

Playing a personal modpack, the game crashed multiple times whenever we were using a diamond axe on several blocks, even when using it on those blocks which don't have a axe-related use.
[crash-2023-07-23_15.39.06-client[1].txt](https://github.com/GL33P-0R4NG3/oreganized/files/12149145/crash-2023-07-23_15.39.06-client.1.txt)

### Mod Version

22.10.11

### Minecraft Version

1.19

**Comment by PssbleTrngle** [comment]
This actually looks like it is caused by the "everythingcopper" mod and not copperative
