### ISSUE TITLE
Many errors in the log as of 1.20.1

### ISSUE THREAD

**Issue by Insane96** [TeamGalena/copperative#38]
### What happened?

I'm making a modpack and while checking the log, I've noticed many errors from recipes and GLM

These are the errors: https://gist.github.com/Insane96/d11a3b25bb7d830967d81fc28e7e7d18

The first one is due to changes to loot tables, iirc alternatives has been changed to "any_of" or something similar. https://gist.github.com/ChampionAsh5357/cf818acc53ffea6f4387fe28c2977d56#or-and-and-composite-lootitemconditions  
The others are just missing the items.

This is the full log: https://gist.github.com/Insane96/36332cd1a2ef44cc11991fa90c9e7e58

### Mod Version

1.1.0

### Minecraft Version

1.20.1

**Comment by PssbleTrngle** [comment]
Thanks, I will update the loot table operator. Not sure if anything about the missing item warnings can be done, but they also don't break anything, just clutter the log which is a bit annoying

**Comment by Insane96** [comment]
For the recipes you can use conditional loading:

https://github.com/Insane96/SurvivalReimagined/blob/1.20.x/src/generated/resources/data/survivalreimagined/recipes/flint_from_gravel.json

In that case I've used the "not" condition, but for other mods compat you usually do just go

```json
{
	"type": "forge:conditional",
	"recipes": [
		{
			"conditions": [
				{
					"type": "forge:mod_loaded",
					"modid": "tconstruct"
				}
			],
			"recipe": {
				...
			}
		}
	]
}
```

**Comment by PssbleTrngle** [comment]
I don't think there are any recipe errors, since these are already only injected if the mod is present. For the loot tables I unfortunately can't do anything
